name: Node.js CI

on:

  pull_request:
    branches: [ master ]

jobs:

  # macos-build:
  #   runs-on: macos-latest
  #   env:
  #     CSC_IDENTITY_AUTO_DISCOVERY: false

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}

  # - name: NPM Install
  #   run: |
  #    npm install
  #    cd ./workers/worker
  #    npm install
  #    cd ../..
  #    npm install -g electron-packager
  #    npm install -g @angular/cli
  #    npm install -g ngx-i18nsupport


  #   - run: npm run electron:mac
    
    # - name: MacOS Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: sliver-gui.dmg
    #     path: release/sliver-*.dmg

  linux-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: NPM Install
      run: |
       npm install
       cd ./main/workers/worker
       npm install
       cd ../..
       npm install -g electron-packager
       npm install -g @angular/cli
       npm install -g ngx-i18nsupport

    - name: Build Linux
      run: npm run electron:linux

    - name: Linux Artifact (deb)
      uses: actions/upload-artifact@v2
      with:
        name: sliver-gui.deb
        path: release/sliver-*.deb
    
    # - name: Linux Artifact (rpm)
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: sliver-gui.rpm
    #     path: release/sliver-*.rpm

  windows-build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM Install
      run: |
        npm install
        cd ./main/workers/worker
        npm install
        cd ../..
        npm install -g electron-packager
        npm install -g @angular/cli
        npm install -g ngx-i18nsupport

    - run: npm run electron:windows

    - name: Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sliver-gui.exe
        path: release/sliver*.exe
